#! /bin/bash
# $Id$
set -o errexit

CASE=test-fetchmailrc
AGPROG='Fetchmail ($["filename": "'$CASE'.in"])
Read (.accounts)'
# kludge: break up the output into lines
S1='s/\$\[/\
\$\[/g'
S2='s/,\] $/,\
\] /g'

NORMALIZE="parseycp -n"

echo "$AGPROG" | ./ag_fetchmailrc | sed -e 1d | $NORMALIZE >$CASE.ycp.tmp
sed -e "$S1" -e "$S2" $CASE.ycp.tmp > $CASE-i.out.tmp
diff -u $CASE-i.out $CASE-i.out.tmp

rm -f $CASE-o.out.tmp
for i in 1 2; do
echo 'Fetchmail ($["filename": "'$CASE'-o.out.tmp"])
Write (.accounts, ' `cat $CASE.ycp.tmp` ')
Write (., nil)' \
    | ./ag_fetchmailrc >/dev/null
diff -u $CASE-o.out $CASE-o.out.tmp
done
